# Generated by Django 3.2.8 on 2021-11-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary', models.TextField(verbose_name='Коментарий')),
                ('data_order', models.DateTimeField(auto_now_add=True, verbose_name='Дата коментария')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
                'ordering': ['data_order'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_gallery', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото галереи')),
            ],
        ),
    ]
